import type { Metadata } from "next";

import "./globals.css";
import { Toaster } from "react-hot-toast";
import TanstackProvider from "./lib/provider/TanstackProvider";


export const metadata: Metadata = {
  title: "Twit Flash",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Toaster />
        <TanstackProvider>
        {children}
        </TanstackProvider>
      </body>
    </html>
  );
}
